changelog:
  categories:
    - title: New Features & Functionalities
      labels: ["*"]
      exclude:
        labels: ["dependencies"]

    - title: Updated Dependencies
      labels: ["dependencies"]
