import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    nursery: "warn",
    pedantic: "off",
    perf: "warn",
    restriction: "off",
    style: "warn",
    suspicious: "warn",
  },
  env: {
    node: true,
    "shared-node-browser": true,
  },
  ignorePatterns: [
    "coverage/**",
    "dist/**",
    "node_modules/**",
    ".task/**",
    "docs/**",
  ],
  options: {
    maxWarnings: 10,
    reportUnusedDisableDirectives: "error",
    respectEslintDisableDirectives: false,
    typeAware: true,
    typeCheck: false,
  },
  plugins: [
    "eslint",
    "import",
    "jsdoc",
    "node",
    "oxc",
    "promise",
    "typescript",
    "unicorn",
  ],
  rules: {
    "capitalized-comments": "off",
    "no-magic-numbers": "off",
    "no-ternary": "off",
    "no-undefined": "off",
    "no-unused-vars": "warn",
    "no-warning-comments": "off",
    "oxc/no-async-await": "allow",
    "oxc/no-optional-chaining": "allow",
    "oxc/no-rest-spread-properties": "allow",
    "sort-imports": "off",
    "typescript/prefer-readonly-parameter-types": "allow",
    "typescript/no-base-to-string": "off",
    "jsdoc/require-param-type": "off",
    "jsdoc/require-returns-type": "off",
    "eslint/max-statements": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/curly": "off",
    "eslint/one-var": "off",
    "eslint/class-methods-use-this": "off",
    "typescript/explicit-member-accessibility": "off",
    "typescript/method-signature-style": "off",
    "import/no-named-export": "off",
    "import/prefer-default-export": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
  },
  overrides: [
    {
      files: ["*.config.ts"],
      rules: {
        "import/no-default-export": "allow",
        "node/no-top-level-await": "allow",
        "typescript/strict-boolean-expressions": "allow",
        "unicorn/max-nested-calls": "allow",
      },
    },
    {
      files: ["**/types/**/*.ts"],
      rules: {
        "import/no-default-export": "error",
        "import/no-named-export": "allow",
      },
    },
  ],
});
