version: "3"

tasks:
  default:
    silent: true
    desc: List all tasks.
    cmd: task --list

  setup:
    desc: Setup the dev environment.
    summary: |
      Setup the development environment.

      This command is involved in setting up the development environment locally. The
      command starts by installing all the necessary Pre-Commit hooks followed by
      installing all the necessary Node.js dependencies.
    cmds:
      - task: setup:pre-commit
      - task: setup:npm

  setup:npm:
    internal: true
    sources: [package.json]
    generates: [pnpm-lock.yaml]

  setup:pre-commit:
    internal: true
    sources: [.pre-commit-config.yaml]
    generates:
      - .git/hooks/commit-msg
      - .git/hooks/pre-commit

  test:
    silent: true
    desc: Run the test suite.
    summary: |
      Run the test suite.

      This command will run the entire test suite using Vitest. Post completion of the
      test execution, Vitest will print out a coverage report which can be used as a
      reference to identify missing test coverage.
    cmd: pnpm test
