version: "3"

tasks:
  default:
    silent: true
    desc: List all tasks.
    cmd: task --list

  setup:
    desc: Setup the dev environment.
    summary: |
      Setup the development environment.

      This command is involved in setting up the development environment locally. The
      command starts by installing all the necessary Pre-Commit hooks followed by
      installing all the necessary Node.js dependencies.
    cmds:
      - task: setup:pre-commit
      - task: setup:npm
      - task: setup:docs

  setup:npm:
    internal: true
    sources: [package.json]
    generates: [pnpm-lock.yaml]

  setup:pre-commit:
    internal: true
    sources: [.pre-commit-config.yaml]
    generates:
      - .git/hooks/commit-msg
      - .git/hooks/pre-commit

  setup:docs:
    internal: true
    dir: ./docs
    sources: [package.json]
    generates: [pnpm-lock.yaml]
    cmd: pnpm install --frozen-lockfile

  test:
    silent: true
    desc: Run the test suite.
    summary: |
      Run the test suite.

      This command will run the entire test suite using Vitest. Post completion of the
      test execution, Vitest will print out a coverage report which can be used as a
      reference to identify missing test coverage.
    cmd: pnpm test

  qa:
    desc: Run code quality checks.
    summary: |
      Run code quality checks.

      This command will run Oxlint and Oxfmt on the source code to enforce a uniform
      coding standard across the entire source code.
    cmds:
      - pnpm lint
      - pnpm format

  build:
    desc: Build and compile the package.
    summary: |
      Build and compile the package.

      This command will compile and build the package in preparation for distribution to
      a registry (like npm.js). Although the locally compiled package will NOT be
      distributed, the purpose of the command is primarily to serve as a sanity check for
      other devs to check of correctness of the compiled package.
    cmd: pnpm build

  all:
    desc: Run the entire development pipeline.
    summary: |
      Run the entire developmnet pipeline.

      This command will run the entire development pipeline, from dependency installation
      to building the package, including running the QA checks on the source code. The
      command is expected to be run as a means of a sanity check to ensure everything
      works as expected.
    cmds:
      - task: setup
      - task: qa
      - task: test
      - task: build

  docs:
    desc: Run the development version of the documentation.
    summary: |
      Run the development version of the documentation.

      This command will run the development version of the documentation. It will change
      the current working directory to the "docs" and run the necessary command to spin up
      the development server for the documentation.
    dir: ./docs
    cmd: pnpm dev --host
